language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test coverage test
  - sbt -jvm-opts travis/jvmopts.test scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
